#!/bin/bash

VLC="cvlc"

vlc_opts="--play-and-exit"
yt_opts=""
yt_post_opts=""
link=""
for arg in "$@"; do
  case $arg in
    --audio)  yt_opts="--extract-audio --audio-quality 0" ;;
    --time)
      offset=$(echo $2 | cut -d "," -f 1)
      duration=$(echo $2 | cut -d "," -f 2)
      ((duration++))
      shift
      shift
      ;;
    --loop)   vlc_opts="${vlc_opts} --loop" ;;
    --random) vlc_opts="${vlc_opts} --random" ;;
    *)        link=`echo $arg | grep "youtube.com\|youtu.be"` ;;
  esac
  shift
done

os=$(([[ -f /etc/lsb-release ]] && grep -q -i "Ubuntu" /etc/lsb-release) \
  && echo "ubuntu" || echo "os x")
if [[ "$os" == "os x" ]]; then
  VLC="vlc"
  [[ -z $link ]] && link=`pbpaste`
else
  [[ -z $link ]] && link=`xclip -selection clipboard -out`
fi

link=`echo "$link" | grep "youtube.com\|youtu.be"`
if [ -z "$link" ]; then
  echo "A youtube link was not found."
  exit
fi

out=$(mktemp -d)
if [[ $link =~ list= ]]; then
  yt_opts="${yt_opts} --ignore-errors"

  directory=`youtube-dl --playlist-items 1 --get-filename \
    --output "%(playlist_id)s" "$link"`
  out="${out}/${directory}"

  mkdir -p ${out}
  youtube-dl $yt_opts --no-part --output "${out}/%(id)s.%(ext)s" \
    "$link" && \
      $VLC $vlc_opts --quiet $out/* &
else
  file=`youtube-dl $yt_opts --get-filename --output "%(id)s.%(ext)s" "$link"`
  out="${out}/${file}"

  if [[ -z $offset ]]; then
    youtube-dl $yt_opts --no-part --output "$out" \
      --exec "$VLC $vlc_opts --quiet {} &" "$link"
  else
    youtube-dl $yt_opts --no-part --output "$out" \
      --postprocessor-args "-ss $offset -t $duration" \
      --exec "$VLC $vlc_opts --quiet {} &" "$link"
  fi
fi
